[network_config]


[DDP]
world_size = 2   # number of available gpus

[optimizer]
lr = 1e-3

[loss]
loss_func = 'hybrid'

[listener]
listener_sr = 16000

[FFT]
n_fft = 512
hop_length = 256
win_length = 512

[train_dataset]
train_folder = '/home/interns/shaoyanguo/gtcrn/SEtrain/dataset_VCTK_new/train/train_dataset.txt'    # txt文件路径
shuffle = true
num_tot = 0
wav_len = 1  # 截取的wav长度

[train_dataloader]
batch_size = 16
num_workers = 1
drop_last = true
pin_memory = true


[validation_dataset]
train_folder = '/home/interns/shaoyanguo/gtcrn/SEtrain/dataset_VCTK_new/valid/valid_dataset.txt'
shuffle = false
num_tot = 0

[validation_dataloader]
batch_size = 1
num_workers = 1
pin_memory = true

[trainer]
epochs = 120
save_checkpoint_interval = 10
clip_grad_norm_value = 3.0
exp_path = '/home/interns/shaoyanguo/gtcrn/SEtrain/exp_3_5'
resume = false
resume_datetime = ''
resume_step = 0
